-- MySQL Script generated by MySQL Workbench
-- Wed Jun 11 16:16:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema rememberthis_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS rememberthis_db DEFAULT CHARACTER SET utf8 ;
USE rememberthis_db;

-- -----------------------------------------------------
-- Table `rememberthis_db`.`node`
-- -----------------------------------------------------
DROP TABLE IF EXISTS rememberthis_db.node;
-- -----------------------------------------------------
-- Table `rememberthis_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS rememberthis_db.`user`;

CREATE TABLE IF NOT EXISTS rememberthis_db.`user` (
  user_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  oidc_id VARCHAR(200) NOT NULL DEFAULT 'default oidc_id')
  ;
  
  CREATE TABLE IF NOT EXISTS rememberthis_db.cloud_node (
  node_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL DEFAULT '0',
  node_text VARCHAR(500) NOT NULL DEFAULT 'Default node text',
  FOREIGN KEY (user_id) REFERENCES `user`(user_id)
  )
;