-- MySQL Script generated by MySQL Workbench
-- Wed Jun 11 16:16:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema rememberthis_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rememberthis_db` DEFAULT CHARACTER SET utf8 ;
USE `rememberthis_db` ;

-- -----------------------------------------------------
-- Table `rememberthis_db`.`node`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rememberthis_db`.`node` ;
-- -----------------------------------------------------
-- Table `rememberthis_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rememberthis_db`.`user` ;

CREATE TABLE IF NOT EXISTS `rememberthis_db`.`user` (
  `user_id` LONG PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL DEFAULT 'name@domain.com');